name: Template check

on: pull_request

jobs:
  template-check:
    name: Template Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ensure template is updated
        run: make template-test git-clean
