name: Template check

on: pull_request

jobs:
  template-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Ensure template is updated
        run: make template-test git-clean
